# This is a basic workflow to help you get started with Actions

name: Testing
on: push

jobs:
  test_project:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django unit tests
      run:
        pip3 install django
        python3 manage.py test
